### ISSUE TITLE
git tag 2.3.0

### ISSUE THREAD

**Issue by cantsin** [ankicommunity/anki-sync-server#107]
I was running into `unsupported sync protocol (10, supported version: 9)` errors because the [nixpkgs anki-sync-server](https://github.com/NixOS/nixpkgs/blob/master/pkgs/servers/ankisyncd/default.nix#L9) package is still set to 2.2.0. 

Hopefully its an easy lift to push up the git tag for `2.3.0` (to this commit https://github.com/ankicommunity/anki-sync-server/commit/4a71447b1d7bd0a7712270ada7bbfae0c8bafcc5). If so, it'll be easier to update on the nixpkgs end then. Thanks!

**Comment by VikashKothary** [comment]
Sorry for the delay. I've haven't been very good at cutting releases, but I will try and create one this weekend.

**Comment by VikashKothary** [comment]
I've created a new release: https://github.com/ankicommunity/anki-sync-server/releases/tag/v2.3.0. I plan on tidying up the changelog but I hope it works for you to start updating the nixpkgs repository. 

I'm going to close this ticket as I feel like this issue should be resolved. Please re-open if there are any issues.
