### ISSUE TITLE
How to sync

### ISSUE THREAD

**Issue by gla23** [ankicommunity/anki-sync-server#116]
How do I get Anki Version ⁨2.1.49 to use my server?

I've followed the instructions for how to get the server running, but I can't even get Anki to stop using ankiweb. All I get is the screenshot below. I've installed the addon and put my ip in the config. I also tried the instructions in the README for "Anki 2.1.28 and above" when the addon did nothing.

![Screenshot 2021-12-12 at 19 56 16](https://user-images.githubusercontent.com/15679104/145727465-23cea716-9de1-434b-899d-90022e8f3349.png)

**Comment by dobefore** [comment]
first you must create account using 'ankisyncctl.py'
after starting sync Server,you will be asked to input account.it is the account anki requires that  you created with 'ankisyncctl.py'

**Comment by gla23** [comment]
Thanks. I had made the account, but didn't try putting the credentials in the AnkiWeb box...
