### ISSUE TITLE
deletion of unused branches to clear confusion

### ISSUE THREAD

**Issue by dobefore** [ankicommunity/anki-sync-server#118]
@VikashKothary ,Hi.Some users may be confused about difference between many branched,especially develop and master.This happens   
sometimes,like #56 ,#117.
How does that sound?

**Comment by VikashKothary** [comment]
So both branches will be needed for our CI strategy. The master (which I should rename to main) should be a stable version of the server. 

I unfortunately have not been very good at cutting releases manually. But that is the goal.

**Comment by dobefore** [comment]
sorry for my partial thought.how about using tags to indicate releases and keep develop as lastest branch like [anki]https://github.com/ankitects/anki
