### ISSUE TITLE
Add github actions for testing and requirement.txt generation

### ISSUE THREAD

**Issue by ohdearaugustin** [ankicommunity/anki-sync-server#125]
Add github actions for  unit testing with multiple python versions and automatic requirement.txt generation on merge into develop branch.

Fix #124 to make unittest working again.

**Comment by VikashKothary** [comment]
Hi @ohdearaugustin, I'm really excited to see your contribution. I hopefully should have time this weekend. 

Thanks for this.

**Comment by VikashKothary** [comment]
Much appreciated.  I've left some comments in your PR. Let me know if you have any questions.
