### ISSUE TITLE
Anki keeps remind me to Check Database

### ISSUE THREAD

**Issue by isudfv** [ankicommunity/anki-sync-server#129]
I mainly add cards to my deck with Anki and memorize them with Ankidroid. 

But once a while Anki complains "please use the Check Database function, then sync again. If problems  persist, please force a full sync in the preferences screen".

And I've fullly synced a million times. What caused the problem?

**Comment by dobefore** [comment]
Could you  lell me te anki version ?

**Comment by isudfv** [comment]
Anki Version ⁨2.1.49 (dc80804a)⁩
Ankidroid 2.9.1
And anki-sync-server is latest release

**Comment by dobefore** [comment]
I havent encountered your problem on Anki 2.1.50(beta).
Can you trproduce this from scratch? As detailed as prssible

**Comment by isudfv** [comment]
it seems sync on Ankidroid caused this problem. Once there's a sync from Ankidroid, the "check database" error pops up. Adding a card on Anki also causes the problem. But everything on Ankidroid is fine.

**Comment by dobefore** [comment]
If possible,Could you record every step you take in detail with 1....3.... ? With new created user and empty anki clients.

**Comment by isudfv** [comment]
1. create user test
2. login with test on Ankidroid and Anki
4. sync on Ankidroid(upload everything from Ankidroid to server)
5. add my previous deck exported from Ankidroid(there is a V2 scheduler problem when exporting, I thought that's it, but the error persist after switching to v1)
6. sync and everything is fine with user test

**Comment by isudfv** [comment]
I tried  delete my user and  start over.
1. delete isudfv with anki-sync-server
2. delete isudfv in src/collections/
3. add isudfv
4. sync from ankidroid
5. download from web on Anki
6. everything is fine so far
7. modify something on ankidroid and sync
8. "check database"

**Comment by isudfv** [comment]
just tried. nothing wrong so far. the problem seems to be solved
