### ISSUE TITLE
Inconsistent project dependencies

### ISSUE THREAD

**Issue by croxxx** [ankicommunity/anki-sync-server#132]
# Observation
This is a small detail I found after digging around the code to analyze #130 and #131. It seems this is related to two recent merge requests #110 and #122.
Without being too familiar with Python tooling, I noticed that the dependency definitions differ between [pyproject.toml](https://github.com/ankicommunity/anki-sync-server/blob/develop/pyproject.toml), [requirements.txt](https://github.com/ankicommunity/anki-sync-server/blob/develop/src/requirements.txt) and [requirements-dev.txt](https://github.com/ankicommunity/anki-sync-server/blob/develop/src/requirements-dev.txt).

|File|Version|
|-|-|
|pyproject.toml|anki = "2.1.49"|
|requirements.txt|anki==2.1.40; python_version >= "3.8"|
|requirements-dev.txt|anki==2.1.49; python_version >= "3.8"|

My assumption would be for those to be identical, yet the requirement explicitly stated in https://github.com/ankicommunity/anki-sync-server/pull/110#issuecomment-921539777 is violated by `requirements.txt`.

# Suggestion
Assuming dependencies are to be exclusively managed by the tool reading `pyproject.toml`, I suggest the following:

- [ ] Remove [requirements.txt](https://github.com/ankicommunity/anki-sync-server/blob/develop/src/requirements.txt) and [requirements-dev.txt](https://github.com/ankicommunity/anki-sync-server/blob/develop/src/requirements-dev.txt) as they are auto-generated on build.
- [ ] Add `requirements.txt` and `requirements-dev.txt` to `.gitignore` to prevent checking in inconsistent versions in the future.
- [ ] Clearly update build documentation stating how dependencies are managed in this project.

**Comment by croxxx** [comment]
Ah, that is a reasonable approach.

In addition to the changes proposed in the PR I can imagine some sort of sanity check downstream.
For example, the Docker build could always recreate requirements files based on the poetry base. That way even bad dependencies cannot "poison" the build and the specific versions are locked anyways. Downside of this approach would be masking errors, of course.

As the immediate issue has been resolved for now and there is changes proposed improving the general behavior, feel free to close this.

**Comment by ohdearaugustin** [comment]
Should be fixed now with #126

**Comment by VikashKothary** [comment]
The PR has been merged. So hopefully we should not have this issue in the future. 

Thank you @croxxx for raising this issue and @ohdearaugustin for your help in resolving it. It is much appreciated.
