### ISSUE TITLE
[Feature Request] LDAP Authentication

### ISSUE THREAD

**Issue by publicdesert** [ankicommunity/anki-sync-server#138]
On my home server I host several services used by multiple users. To simplify user management, I am running an LDAP server which most of my services are connected to.
If the Anki Sync Server supported LDAP auth, it would be really useful for me. Would implementing this in the future be feasible?

**Comment by VikashKothary** [comment]
Hi @publicdesert, so I would say that the use of an LDAP server with the anki-sync-server is quite an advanced use case for most people. But depending on how much up-votes this ticket gets, it might be something we'd need to look into.

Could you provide some insight on what changes would need to be implemented to support an LDAP server?

**Comment by publicdesert** [comment]
Closing this issue since I personally have no use for this feature anymore and noone else showed interest in it.
