### ISSUE TITLE
Create Releases with Github

### ISSUE THREAD

**Issue by ohdearaugustin** [ankicommunity/anki-sync-server#147]
It would be nice to automate releases with github action.
So when you push a tag, it automatically will merge the develop branch to the master branch and release it.

Will open PR.

**Comment by ohdearaugustin** [comment]
Test release can be found in my [fork](https://github.com/ohdearaugustin/anki-sync-server/releases/tag/v2.4.3).

**Comment by VikashKothary** [comment]
Oooh this is very nice. I'll review the PR right now. Thanks so much for your contribution.
