### ISSUE TITLE
Link in README leading to nothing

### ISSUE THREAD

**Issue by juli-99** [ankicommunity/anki-sync-server#161]
The link https://github.com/jdoe0/ankisyncd leads to nothing (error 404).
It is used in the line "This version is a fork of [jdoe0/ankisyncd](https://github.com/jdoe0/ankisyncd)." in [README.md](https://github.com/ankicommunity/anki-sync-server/tree/develop#readme).

**Comment by VikashKothary** [comment]
Hi @juli-99,

Thank you for bringing this to my attention. 

It seems that the user no longer exists as such I've removed the broken link. I've also refactored the README with an Acknowledgements section. Please have a look: https://github.com/ankicommunity/anki-sync-server/commit/a9a2bb56468395a22fd76a6a527e09b01ea78267.

Please feel free to close this issue if you're happy with the change. 

Thank you for helping to improve our documentation.
