### ISSUE TITLE
Addon does not set the sync-server url in Anki versions > 2.1.26

### ISSUE THREAD

**Issue by kalehmann** [ankicommunity/anki-sync-server#19]
As of Anki version 2.1.28, the server address is not affected by the addon anymore.

## What did I do?

I installed [Anki 2.1.28](https://github.com/ankitects/anki/releases/tag/2.1.28) and created an addon with the following content:

```
import anki.sync, anki.hooks, aqt

addr = "http://127.0.0.1:27701/" # put your server address here
anki.sync.SYNC_BASE = "%s" + addr
def resetHostNum():
    aqt.mw.pm.profile['hostNum'] = None
anki.hooks.addHook("profileLoaded", resetHostNum)
```

Then I started Anki and hit the **Sync** button.

## What did I expect to happen?

I expected Anki to make a request to the url specified in the addon.

## What did happen instead?

Anki made a request to `https://sync.ankiweb.net/msync/` instead.

## Further information

The urls used for synchronizaton are hardcoded to `https://sync.ankiweb.net` since the commits [0e5b7da62aa0fd3726ca958f1cdae265d2dc0d91](https://github.com/ankitects/anki/commit/0e5b7da62aa0fd3726ca958f1cdae265d2dc0d91) and [529e89f48e747904ffd9c8ebac09739fb410bcaf](https://github.com/ankitects/anki/commit/529e89f48e747904ffd9c8ebac09739fb410bcaf). 
Therefore they cannot be easily changed by the addon anymore.

**Comment by AntonOfTheWoods** [comment]
Yeah, I keep telling people the upstream author really doesn't care about other server implementations. This is at least going to mean changing your hosts file (or similar, though that means you need to be able to use port 80). Is it still possible to allow for bad certs on the desktop client?

**Comment by kalehmann** [comment]
Wow, I am blind 🤦 

Thank you for pointing this out. With

```python
import os

addr = "http://127.0.0.1:27701/"

os.environ["SYNC_ENDPOINT"] = addr + "sync/"
os.environ["SYNC_ENDPOINT_MEDIA"] = addr + "msync/"
```

as addon for Anki and 


```
server {
        listen      27701;
        server_name default;

        location / {
                proxy_pass https://sync3.ankiweb.net/;
        }
}
```

as local nginx proxy, I am able to intercept synchronization requests with Anki versions >= 2.1.28.
