### ISSUE TITLE
org.JSONException: a JSONObject text must begin with '{' at character 1 of Anki Sync Server

### ISSUE THREAD

**Issue by genedan** [ankicommunity/anki-sync-server#27]
Hello,

First of all, thanks for your efforts in modernizing this package. I was prepared to spend a lot of time trying to learn the library and you have helped tremendously. I have gotten my server to work with Anki desktop through a https reverse proxy.

However, I'm having trouble with AnkiDroid.  I am using version 2.13.3. Namely, this instruction in the README:

```
Use the same base url for both the Sync url and the Media sync url. Do not append /sync and /msync as the default setup does.
```

I have set up my fields as follows:

**Sync url:** https://myurl.com/

**Media sync url**: https://myurl.com/

However, when doing so, I get the following error upon media sync:

![Screenshot_20200923-170248_AnkiDroid](https://user-images.githubusercontent.com/6165650/94079189-12db4a00-fdc4-11ea-8c11-52822393177e.jpg)

The cards sync, so I am connecting to the server. However the media sync is where it fails.

A second observation is that despite the instructions telling me not to append my media sync url with 'mysnc', when I do that:

**Media sync url**: https://myurl.com/msync

It actually syncs. However it took 20 minutes to do so whereas with Tsudoko's version it used to take a second or two. I suspect it's crawling through my entire media folder of 47,000 files. See:

https://github.com/tsudoko/anki-sync-server/issues/26

Then again, that was fixed here:

https://github.com/ankicommunity/anki-sync-server/commit/e8f274ee843111eae7f91679cbf86d782504fb63

I tried adding some media again and then it took just a second. So maybe this problem just happens after version upgrades or when setting up a new server or something like that. But I'm still appending 'msync' to my media sync url, so I'm wondering if that is indeed not the right thing to do.

Thanks!

**Comment by rreuvekamp** [comment]
This just happened to me as well after setting up the sync server and configuring AnkiDroid to use it.
I only had one collection in AnkiDroid and hadn't connected to the sync server from any other client. 

Appending "/msync" to the media sync url fixed it for me as well. Thanks for documenting!

**Comment by soulker** [comment]
Media Sync URL fixed must match the configuration base_ media_ The URL is consistent, otherwise it will return "anki sync server", which is not a JSON
