### ISSUE TITLE
See if this can be combined with other forks

### ISSUE THREAD

**Issue by VikashKotharyWork** [ankicommunity/anki-sync-server#3]
https://github.com/tsudoko/anki-sync-server

**Comment by Sterrs** [comment]
Oops I didn't see this. I'll delete my other issue sorry.

**Comment by VikashKothary** [comment]
Update: The main problem with this is that tsudoko branched off from an older commit and we'll need to consolidate the two git histories. 

A thought might be to make https://github.com/tsudoko/anki-sync-server's repo the master until I find the time to do so.

**Comment by Jedliu** [comment]
From [tsudoko/anki-sync-server](https://github.com/tsudoko/anki-sync-server) anki-bundled is 2.1.11, I don't know if there is much difference. Would you please give some hints? I will check if have time to look into this.

**Comment by VikashKothary** [comment]
Well there's a considerable difference between the number of commits, and tsudoko's fork is a bit of a rewrite. 

What I'll probably try and do, is take the tsudoko's master and merge this repo's master. The trouble is most of the files in tsudoko's master will be deleted causing conflicts. Once all new files have been added, we'll need to transfer the functionality which is a bit more complex. 

One thing that is lost in tsudoko's repo is the API. While it makes sense in his repo, I'd like to keep the functionality in some form. Preferability as a plugin.

**Comment by Jedliu** [comment]
Yes, I agree. The API part is something I need mostly.

**Comment by VikashKothary** [comment]
I've added tsudoko's branch as 'develop'. And it's been now setup as the default.

**Comment by VikashKothary** [comment]
This has almost been resolved. The last remaining point is listing all the different forks used in this project in the README.

It should be clear that this project supersedes those projects.

**Comment by VikashKothary** [comment]
Super-seeded by https://github.com/ankicommunity/anki-sync-server/issues/3

**Comment by AdrienLemaire** [comment]
This is #3 ...
