### ISSUE TITLE
v2 scheduler support

### ISSUE THREAD

**Issue by genedan** [ankicommunity/anki-sync-server#31]
There was a pull request that never got merged with Tsudoko's repo concerning the v2 scheduler.

https://github.com/tsudoko/anki-sync-server/pull/53

I applied this to my own copy and it has been working for the last few months without issue. Just leaving this here if anyone else is also using the v2 scheduler.

**Comment by VikashKothary** [comment]
Thanks for sharing this, I'll take the action of opening a PR for that branch on this repo. Once it has been reviewed, we can merge it in.

**Comment by VikashKothary** [comment]
Sorry all, I only get to look at this during my weekends. And my weekends have been quite busy recently.

This is still on my todo list but if anyone else has the time to pick this up. It'll be much appreciated.

P.S. @HuuLane I love a good emoji reaction. Don't worry we'll get the moving asap.

**Comment by VikashKothary** [comment]
@cecini has graciously created a PR for this issue: https://github.com/ankicommunity/anki-sync-server/pull/36.

But still pending the README update but merging this PR should close this issue.

**Comment by rwmpelstilzchen** [comment]
I see this issue is still open. Is there a reason to avoid using anki-sync-server with the V2 scheduler? Is it well tested?

**Comment by VikashKothary** [comment]
@rwmpelstilzchen Good point. I've not heard of any issues. I'll close this and we can re-open if needed.
