### ISSUE TITLE
Anki Win desktop 2.1.35 sync fail:please  use the check database function,then sync again

### ISSUE THREAD

**Issue by dobefore** [ankicommunity/anki-sync-server#32]
Hi,there.
**reproduce**:
1.when I add a user on server and input it on PC Anki,first hit sync button,everything was Ok.Then I tried to add card with plain text or pictures(media) and synced,the following dialog popped out.
![Snipaste_2020-10-03_18-43-58](https://user-images.githubusercontent.com/46564102/94989589-8a6d5e00-05a8-11eb-8b05-7eded80bdb3d.png)
I guess **It cannot sync after operations of add/deleteing cards/decks and learning trace**.

2.Then I go to **tools-->preferences-->scheduling**,select Anki 2.1 scheduler checkbox and closes.And I hit sync button,It prompts me to select upload and download .Then I hit download from ankiweb,It seems that works and the effect is equivalent to upload.Yet 
upload button will show the check database dialog.

3.I wait for several minutes until logs like `collection thread running close` was printed on server window,I hit sync button again,the tiring check database dialog pop out once more.I must select Anki 2.1 scheduler in the preferences ,If I want to use it to sync.
And 2.1.33 is the same
**above all, It works repeating this operation(I go to tools-->preferences-->scheduling ,select Anki 2.1 scheduler checkbox and closes and download (not upload) in order to add/delete or change learing process)**

**Comment by inevity** [comment]
Just in the preferences -netowork， select next sync。then close anki。then start anki， to full sync the anki.
if just select next sync, and then click sync ,the dialog "please use the check database funciton" always appear!
Now the dialog disappear.

**Comment by dobefore** [comment]
Thanks for your reply! It worked fine after following your suggestions.Yet,
another Problem appears.
After checking database and media ,the Window pops out,`Ankiweb encountered a problem.Please try again in a few minutes`
![rtengtuant](https://user-images.githubusercontent.com/46564102/96364139-c4735e00-116b-11eb-976d-28387c3543d7.png)
Is there any amendment?

**Comment by inevity** [comment]
Yes, not to delete unused meida. 
Mabye the sync server version not compatile with the desktop version/ankiandroid. 

Just no time to figure it out now

**Comment by dobefore** [comment]
@cecini  ,Thanks for your fixes.yet the problem seems still existing described as this issue. When I review
cards on **desktop Anki**  ，followings are the optputs:
`[2020-10-30 11:54:25,357]:INFO:ankisyncd:sanity check failed with server: [[5, 1, 0], 55458, 38630, 361, 0, 17, 21, 2] client: [[0, 0, 0], 55458, 38630, 361, 0, 17, 21, 2]
[2020-10-30 11:54:25,358]:INFO:ankisyncd.http:192.168.43.196 "POST /sync/sanityCheck2 HTTP/1.1" 200 119
[2020-10-30 11:54:25,364]:INFO:ankisyncd.http:192.168.43.196 "POST /sync/abort HTTP/1.1" 404 154`

and **upload button** doesn't work , the crash log:`Ankiweb username or password incorrect`.here are my environment:
OS: Win10
PC Anki:2.1.35
python:3.9
mod :anki==2.1.36
ankirspy==2.1.36

**Comment by dobefore** [comment]
@ cecini Could I ask a question about building from anki source? I build it on Win10 ,It seems I lost one locale?
`Compiling *.po...
/anki.mo”写入出错: No such file or directoryin\msgfmt.exe: 打开“../aqt_data/locale/gettext/af/LC_MESSAGES
error building repo/desktop/af/anki.po
make[1]: *** [Makefile:50: .build/i18n] Error 1
make[1]: Leaving directory '/cygdrive/d/software/vscode_project/anki/qt'`

**Comment by cecini** [comment]
> [2020-10-30 11:54:25,357]:INFO:ankisyncd:sanity check failed with server: [[5, 1, 0], 55458, 38630, 361, 0, 17, 21, 2] client: [[0, 0, 0], 55458, 38630, 361, 0, 17, 21, 2]

apply the fix https://github.com/ankitects/anki/pull/805 .

> **upload button** doesn't work

Just have not the window anki . Where is the upload button?


https://github.com/ankitects/anki/blob/master/README.development


> building from anki source?

Did you follow the doc https://github.com/ankitects/anki/blob/master/README.development? PyCharm way or VS way?

**Comment by dobefore** [comment]
Oh,How wonderful it is! Really Appreciate your continunious fix. It work fine .Thanks

**Comment by dobefore** [comment]
> @ cecini Could I ask a question about building from anki source? I build it on Win10 ,It seems I lost one locale?
> `Compiling *.po... /anki.mo”写入出错: No such file or directoryin\msgfmt.exe: 打开“../aqt_data/locale/gettext/af/LC_MESSAGES error building repo/desktop/af/anki.po make[1]: *** [Makefile:50: .build/i18n] Error 1 make[1]: Leaving directory '/cygdrive/d/software/vscode_project/anki/qt'`

here are my solution :run command in unix_like CMD:eg git bash

**Comment by dobefore** [comment]
The problem seems disappearing after creating and deleting a deck **On PC Anki** and syncing.However,When deleting the  deck   created on PC and syncing **On Ankidroid**,and then sync On PC Anki,the problem will appear Even though I applied ankitects/anki#805 and fixes in Ankicommunity

**Comment by cecini** [comment]
What is the log line  sanity check failed with server:

**Comment by dobefore** [comment]
```
Running meta(*[], **{'v': 10, 'cv': 'anki,2.1.36 (6b0b3fcd),win:10'})
[2020-11-03 18:51:36,971]:INFO:ankisyncd.http:192.168.43.196 "POST /sync/meta HTTP/1.1" 200 146
[2020-11-03 18:51:36,977]:INFO:ankisyncd.CollectionThread[puyuan]:Running start(*[], **{'minUsn': 81, 'offset': None, 'lnewer': False})
[2020-11-03 18:51:36,980]:INFO:ankisyncd.http:192.168.43.196 "POST /sync/start HTTP/1.1" 200 78
[2020-11-03 18:51:36,990]:INFO:ankisyncd.CollectionThread[puyuan]:Running applyChanges(*[], **{'changes': {'models': [], 'decks': [[], []], 'tags': []}})
[2020-11-03 18:51:36,995]:INFO:ankisyncd.http:192.168.43.196 "POST /sync/applyChanges HTTP/1.1" 200 64
[2020-11-03 18:51:37,001]:INFO:ankisyncd.CollectionThread[puyuan]:Running chunk(*[], **{})
[2020-11-03 18:51:37,002]:INFO:ankisyncd.http:192.168.43.196 "POST /sync/chunk HTTP/1.1" 200 54
[2020-11-03 18:51:37,008]:INFO:ankisyncd.CollectionThread[puyuan]:Running applyChunk(*[], **{'chunk': {'done': True}})
[2020-11-03 18:51:37,009]:INFO:ankisyncd.http:192.168.43.196 "POST /sync/applyChunk HTTP/1.1" 200 4
```

```
[2020-11-03 18:51:37,028]:INFO:ankisyncd.CollectionThread[puyuan]:Running sanityCheck2(*[], **{'client': [[0, 0, 0], 55460, 38632, 398, 13, 17, 21, 2], 'full': True})
[2020-11-03 18:51:37,114]:INFO:ankisyncd:sanity check failed with server: [[1, 0, 13], 55460, 38632, 398, 13, 17, 21, 2] client: [[0, 0, 0], 55460, 38632, 398, 13, 17, 21, 2]
[2020-11-03 18:51:37,115]:INFO:ankisyncd.http:192.168.43.196 "POST /sync/sanityCheck2 HTTP/1.1" 200 122
[2020-11-03 18:51:37,119]:INFO:ankisyncd.http:192.168.43.196 "POST /sync/abort HTTP/1.1" 404 154```

**Comment by dobefore** [comment]
I just create a deck with a card and sync to server On PC Anki.Then I sync On Ankidroid,the **sync error** dialog appears prompts me to select either to upload from local or download from remmoat

**Comment by cecini** [comment]
The pr [Fix: conf should be synced to client when server mod time is newer #52](https://github.com/ankicommunity/anki-sync-server/pull/52) should fix this PC/Android sync issue.

**Comment by dobefore** [comment]
@cecini Oh,greate!really appreciate your help,It surely worked the problem out. Yet this is only fit into 2.1.36 .With  2.1.35 and before this is not compatible ,Maybe non-paired anki and ankirspy modules?

**Comment by cecini** [comment]
Not clear about it.  As i knew, since 2.1.28  including 2.1.28.,all rust/pylib version is just small and incremental change..

**Comment by DavyLiucc** [comment]
how can i get ankirspy:2.1.36 ready? thanks. it shows as below,where can i download ankirspy:2.1.36?
ERROR: Could not find a version that satisfies the requirement ankirspy==2.1.36
(from -r src/requirements.txt (line 2)) (from versions: 2.1.25, 2.1.26, 2.1.28,
2.1.29, 2.1.30, 2.1.31, 2.1.32, 2.1.33, 2.1.34, 2.1.35)
ERROR: No matching distribution found for ankirspy==2.1.36 (from -r src/requirem
ents.txt (line 2))

**Comment by dobefore** [comment]
@DavyLiucc  HI.As the pip-install-error shows,module anki 2.1.36 has not been published.Until then,You can build it from source [](https://github.com/ankitects/anki/blob/master/docs/development.md)
