### ISSUE TITLE
Why the anki desktop use HTTP 1.0?

### ISSUE THREAD

**Issue by inevity** [ankicommunity/anki-sync-server#35]
Is there anyhone point where the code use the http1.0 version to req/response http req on anki desktop?

Just confirmation that ankiandroid /anki desktop always send http 1.0 req to sync server.
We should upgrade to http 1.1?

**Comment by inevity** [comment]
some related https://github.com/ankicommunity/anki-sync-server/issues/21 
Move on from the WSGI environment to something that supports at least HTTP 1.1 #21

**Comment by VikashKothary** [comment]
Hi @inevity, thanks for this issue. I see you've marked this similar to #21. 

Do you think we can combine the two tickets so we can talk about upgrading to HTTP 1.1 all in one ticket?

**Comment by inevity** [comment]
Yes ,please combine the two's.
