### ISSUE TITLE
  I have no way to update the anki version. The synchronization server reported an error

### ISSUE THREAD

**Issue by liu-hz** [ankicommunity/anki-sync-server#39]
After anki 1.28, login display user and password error. I update the previous code according to the updated anki sync server to work with the latest version of anki ා 20, but the server still cannot be used and an error is reported

File "/usr/lib/python3.6/ runpy.py ",line 193 in _ run_ module_ As_ main

"Wei" main__ ",mod_ spec)

File "/home/anki/anki/anki-sync-server/ankisyncd/__ main__ .py" line 8, in <module> import ankisyncd.sync_ App

File "/home/anki/anki/anki-sync-server/ankisyncd/sync_ app.py " line37, in <module> import anki.db

ModuleNotFoundError: No module named 'anki'

Please tell me how to deal with this problem. There are many documents updated in question 20. Do I need to update these documents? Thank you for your guidance

**Comment by cecini** [comment]
The server you use anki python dependency, you need pip install anki/ankirspy. please see src/requirements.txt.
What is anki ා 20?

**Comment by dobefore** [comment]
just try this 
`pip uninstall anki`
`pip install anki` or `pip3 install anki`

**Comment by liu-hz** [comment]
> 只是尝试这个
> `pip uninstall anki`
> `pip install anki`或`pip3 install anki`


i install pip and try this order pip install anki it tell me Could not find a version that satisfies the requirement anki (from versions)  no matching distribution found ankirspy

**Comment by liu-hz** [comment]
i try the order it tell me Could not find a version that satisfies the requirement anki (from versions)  no matching distribution found ankirspy

**Comment by liu-hz** [comment]
> `pip install anki`或`pip3 install anki`



Can you tell me how to install a new PIP install anki or PIP3 install anki? Thank you very much. I'm a rookie. I can't operate the fuzzy steps successfully. How can you tell me how to build a new anki sync server? Thank you very much

**Comment by dobefore** [comment]
Anki 2.1.28 and later cannot work well curently ,
`pip install anki==2.1.35`

**Comment by liu-hz** [comment]
> Anki 2.1.28 and later cannot work well curently ,
> `pip install anki==2.1.35`

Do you mean that currently, anki sync server can't support version 2.1.28 very well. Can your server support version 1.28 and later? Your suggestion is not to use the version after 1.28, right?

**Comment by cecini** [comment]
Look at depend at  https://github.com/ankicommunity/anki-sync-server/blob/develop/src/requirements.txt 
anki==2.1.32
ankirspy==2.1.32.
Look Like since 2.1.28 including 2.1.28, anki/ankirspy have drastly change. So maybe 2.1.28 will support .But suggest you install this 2.1.32 version by pip install anki==2.1.32 or  pip install -r src/requirements.txt.

**Comment by liu-hz** [comment]
I have created a new Ubuntu server and intend to re deploy the anki sync server and use the code of ankicommunity / anki sync server to build it. Now I have downloaded the code. Next, how to install it? Please advise me. Thank you. As shown in the figure, install python3 PIP has been installed.


root@anki:/home/anki# ls
root@anki:/home/anki# cd /
root@anki:/# cd anki
root@anki:/anki# ls
root@anki:/anki# git clone https://github.com/ankicommunity/anki-sync-server.git                              Cloning into 'anki-sync-server'...
remote: Enumerating objects: 186, done.
remote: Counting objects: 100% (186/186), done.
remote: Compressing objects: 100% (86/86), done.
remote: Total 2084 (delta 116), reused 149 (delta 100), pack-reused 1898
Receiving objects: 100% (2084/2084), 552.67 KiB | 19.00 KiB/s, done.
Resolving deltas: 100% (1324/1324), done.
root@anki:/anki# cd anki-sync-server
root@anki:/anki/anki-sync-server# git submodule update --init
root@anki:/anki/anki-sync-server# cd anki-bundled/
bash: cd: anki-bundled/: No such file or directory
root@anki:/anki/anki-sync-server# ls
config  COPYING  docs  Makefile  notebooks  poetry.lock  pyproject.toml  README.md  scripts  src  tests
root@anki:/anki/anki-sync-server#

**Comment by liu-hz** [comment]
pip3 install -r src/requirements.txt
Collecting anki==2.1.32 (from -r src/requirements.txt (line 1))
  Could not find a version that satisfies the requirement anki==2.1.32 (from -r src/requirements.txt (line 1)) (from versions: )
No matching distribution found for anki==2.1.32 (from -r src/requirements.txt (line 1))

**Comment by liu-hz** [comment]
should i need install the anki-2.1.32-linux-amd64.tar.bz2  for server

**Comment by dobefore** [comment]
make sure python3 version >=3.7 ?

**Comment by liu-hz** [comment]
Do I need to install anki-2.1.32-linux-amd64 tar.bz2 This file is on the server. I will check the python version later. If it is lower than 3.7, I will upgrade it?

**Comment by dobefore** [comment]
No need to install Linux Anki client app, Windows env is Ok if you aren't familiar with Linux

**Comment by liu-hz** [comment]
root@anki:/anki# python3.7 --version
Python 3.7.5

**Comment by liu-hz** [comment]
root@anki:/anki/anki-sync-server# pip install -r requirements.txt
Traceback (most recent call last):
  File "/usr/lib/command-not-found", line 28, in <module>
    from CommandNotFound import CommandNotFound
  File "/usr/lib/python3/dist-packages/CommandNotFound/CommandNotFound.py", line 19, in <module>
    from CommandNotFound.db.db import SqliteDatabase
  File "/usr/lib/python3/dist-packages/CommandNotFound/db/db.py", line 5, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'




Is this due to the wrong installation of my Python 3.7?

**Comment by dobefore** [comment]
pip3 install -r requirements.txt ?

**Comment by liu-hz** [comment]
pip3 install -r src/requirements.txt
bash: /usr/bin/pip3: No such file or directory




> pip3 install -r requirements.txt ?


The original version of the original version is 3.6. I upgraded it to 3.7

Through these two soft connections sudo Ln-S /usr/bin/python 3.7 /usr/bin/python 3

Sudo Ln-S /usr/bin/pip3.7 /usr/bin/pip3 has been modified, but it seems that there is no way to use PIP3 when it is installed?

**Comment by liu-hz** [comment]
I readjusted the python environment and updated the PIP library PIP install - R Src/ requirements.txt It is being installed normally. Do I need to make any adjustment after installation?

**Comment by liu-hz** [comment]
ERROR: Command errored out with exit status 1:
   command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-v8o8rgvv/psutil/setup.py'"'"'; __file__='"'"'/tmp/pip-install-v8o8rgvv/psutil/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-ndntv02o
       cwd: /tmp/pip-install-v8o8rgvv/psutil/
  Complete output (45 lines):
creating build/temp.linux-x86_64-3.7/psutil
    x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_SIZEOF_PID_T=4 -DPSUTIL_VERSION=572 -DPSUTIL_LINUX=1 -I/usr/include/python3.7m -c psutil/_psutil_common.c -o build/temp.linux-x86_64-3.7/psutil/_psutil_common.o
    psutil/_psutil_common.c:9:10: fatal error: Python.h: No such file or directory
     #include <Python.h>
              ^~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-va5zt6tm/psutil/setup.py'"'"'; __file__='"'"'/tmp/pip-install-va5zt6tm/psutil/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-rgx698yd/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.7/psutil Check the logs for full command output.




When executing PIP command, what should I do?

**Comment by liu-hz** [comment]
it can be work thank you dobefore and cecini thank you so much
