### ISSUE TITLE
about Anki synchronization file size limit

### ISSUE THREAD

**Issue by liu-hz** [ankicommunity/anki-sync-server#40]
The media file is too large for anki synchronization. Unable to synchronize. The problem is ankisyncd.conf Is it modified in the document?

**Comment by cecini** [comment]
The error is emittd to ankisyncserver by the proxy. For nginx,  you  should  set client_max_body and client_body_buffer_size to bigger value.

**Comment by liu-hz** [comment]
> The error should be resolved by placing a proxy before the ankisyncserver . For nginx, you should set client_max_body and client_body_buffer_size to bigger value.
thank you very much  i had fix this problem thank you cecini you help me again。
