### ISSUE TITLE
Conflicting Git Histories.

### ISSUE THREAD

**Issue by VikashKothary** [ankicommunity/anki-sync-server#43]
Raised by @AntonOfTheWoods in #2 and #33.

**Comment by VikashKothary** [comment]
Hi @AntonOfTheWoods,

So I understand where you're coming from. There are a lot of different forks that were used to get this project to where it is now. But our current project is very different from them and is just going to get more different. And because of that, there's not as much value from the Git History.

That being said, deleting this git history is controversial. The conflicts won't be an issue when we're a standalone repo. And git histories are mainly used for troubleshooting, as such, they're a nice fallback to have. 

Deleting the git history is also a destructive change which means that if we want to revert that change in the future, it will be a pain to do it.

But I see wisdom in your suggest, so here's a potential compromise:

- We copy the code from this repo into the djankiserv repo in parallel with the existing code. 
- Lock this repo (issues/PRs/etc) 
- and then have the https://github.com/ankicommunity/anki-sync-server url redirect to djankiserv's repo. 

The advantages would be:

- This will give you a fresh git history with only the code. 
- It will make combining the two projects easier.
- No destructive git actions so not chance of losing data

This approach has disadvantages as well so we should only implement this if we're sure there is value to the users from this.

**Comment by AntonOfTheWoods** [comment]
Does https://github.com/ankicommunity/anki-sync-server/issues/42#issuecomment-720229588 answer for my take on this?

**Comment by VikashKothary** [comment]
I'm going consider this ticket closed. In the end, I want to say your suggestion was correct. And we should simplify the relationship between the different forks. As such, that is covered by this issue: https://github.com/ankicommunity/anki-sync-server/issues/3.
