### ISSUE TITLE
Multimedia files can be synchronized, but pictures can't be displayed and audio can't be played

### ISSUE THREAD

**Issue by liu-hz** [ankicommunity/anki-sync-server#44]
I made a card on my mobile phone and put a picture in it. But when I synchronize the data to the computer, it can't be viewed normally and the pictures can't be displayed. 

And the audio is the same, can be synchronized, but mp3 can not play sound, media files can be synchronized, but can not be used, what is the problem?
![error](https://user-images.githubusercontent.com/71445465/97934767-99b31780-1db1-11eb-8ff0-4f2c5a0881ae.png)

How to deal with this problem? Thank you very much.

**Comment by dobefore** [comment]
Do you apply PR code to your server? After doing it,I find it wroks fine When syncing pictures

**Comment by cecini** [comment]
The png you pasted  here cannot be downloaded.

**Comment by liu-hz** [comment]
Currently, I have the following new patches:

fix the remove deck lead server crash issue ankicommunity#28,change i…
fix:once client items in graves have been remove  …
ensure mediadir exsit in the case full sync ok after delete server co…

Ubuntu 18.04
PC Anki：2.1.35 
python：3.7.5
mod：anki == 2.1.32
ankirspy == 2.1.32

Can you tell me which problem I need to update in order to solve the problem that this image can't be displayed.

Or do I need to update the software version,

i git from ankicommunity/anki-sync-server, about Updated anki-sync-server to work with the latest version of Anki is change Is it packaged in SRC file? Does it need to be modified separately?  thank you so much

**Comment by dobefore** [comment]
The newer fixes are 4 days ago ,You could git fetch and pull the latest code from the ankicommunity

**Comment by liu-hz** [comment]
> The newer fixes are 4 days ago ,You could git fetch and pull the latest code from the ankicommunity or just directly modify the code from [PR](https://github.com/ankicommunity/anki-sync-server/pull/36/files) almostly contributed by cecini

So I get the code through git again and install it again? In this way, the previous related patches should take effect? I'll try. If there is any problem, I'll ask again. Thank you very much

**Comment by liu-hz** [comment]
Traceback (most recent call last):
  File "/anki/anki-sync-server/src/ankisyncd/thread.py", line 98, in _run
    ret = self.wrapper.execute(func, args, kw, return_queue)
  File "/anki/anki-sync-server/src/ankisyncd/collection.py", line 45, in execute
    ret = func(*args, **kw)
  File "/anki/anki-sync-server/src/ankisyncd/sync_app.py", line 573, in run_func
    res = handler_method(**keyword_args)
  File "/anki/anki-sync-server/src/ankisyncd/sync_app.py", line 205, in uploadChanges
    processed_count = self._adopt_media_changes_from_zip(z)
  File "/anki/anki-sync-server/src/ankisyncd/sync_app.py", line 274, in _adopt_media_changes_from_zip
    assert self.col.media.lastUsn() == oldUsn + processed_count  # TODO: move to some unit test
AssertionError
Traceback (most recent call last):
  File "/usr/lib/python3.8/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/usr/local/lib/python3.8/dist-packages/webob/dec.py", line 129, in __call__
    resp = self.call_func(req, *args, **kw)
  File "/usr/local/lib/python3.8/dist-packages/webob/dec.py", line 193, in call_func
    return self.func(req, *args, **kwargs)
  File "/anki/anki-sync-server/src/ankisyncd/sync_app.py", line 550, in __call__
    result = self._execute_handler_method_in_thread(url, data, session)
  File "/anki/anki-sync-server/src/ankisyncd/sync_app.py", line 582, in _execute_handler_method_in_thread
    result = thread.execute(run_func, kw=keyword_args)
  File "/anki/anki-sync-server/src/ankisyncd/thread.py", line 79, in execute
    raise ret
  File "/anki/anki-sync-server/src/ankisyncd/thread.py", line 98, in _run
    ret = self.wrapper.execute(func, args, kw, return_queue)
  File "/anki/anki-sync-server/src/ankisyncd/collection.py", line 45, in execute
    ret = func(*args, **kw)
  File "/anki/anki-sync-server/src/ankisyncd/sync_app.py", line 573, in run_func
    res = handler_method(**keyword_args)
  File "/anki/anki-sync-server/src/ankisyncd/sync_app.py", line 205, in uploadChanges
    processed_count = self._adopt_media_changes_from_zip(z)
  File "/anki/anki-sync-server/src/ankisyncd/sync_app.py", line 274, in _adopt_media_changes_from_zip
    assert self.col.media.lastUsn() == oldUsn + processed_count  # TODO: move to some unit test
AssertionError


I rebuilt an anki server, got the code through git, and then installed it. Now, when I synchronize, do you have the above problems?

**Comment by dobefore** [comment]
mod Anki==2.1.36 currently is not published and can be self built. I guess 2.1.32 Maybe works the same. I didnt encouter that problem.You may correctly modify the code from PR

**Comment by liu-hz** [comment]
> mod Anki==2.1.36 currently is not published and can be self built. I guess 2.1.32 Maybe works the same. I didnt encouter that problem.You may correctly modify the code from PR
@cecini @dobefore 
I changed the version in the environment file to 2.1.35, which can be installed, but the above error occurs. Now I don't know which version I should repair to solve the problem that pictures and audio can't be played. Can you tell me what I should update?

About updated anki sync server to work with the latest version of anki?



Can I have a point, please? I'm confused
thank you so much

**Comment by dobefore** [comment]
U may need to apply PR changes by modifying your server code from PR files changes  [PR](https://github.com/ankicommunity/anki-sync-server/pull/36/files)

**Comment by liu-hz** [comment]
> U may need to apply PR changes by modifying your server code from PR files changes [PR](https://github.com/ankicommunity/anki-sync-server/pull/36/files)

Ok 

I try to modify the code here, all the changes, try, thank you.
on my old server it can be work just Cannot display pictures and play sounds

**Comment by liu-hz** [comment]
> U may need to apply PR changes by modifying your server code from PR files changes [PR](https://github.com/ankicommunity/anki-sync-server/pull/36/files)

I replaced all code in PR to the server, but this problem still can't be solved. Is it necessary to use a newer version. At present, pictures and audio still can't be displayed and played normally. How to deal with it


Ubuntu 18.04 
PC Anki：2.1.35 
python：3.7.5 
mod：anki == 2.1.32 
ankirspy == 2.1.32

**Comment by dobefore** [comment]
try with adding a new profile or adding a new server account

**Comment by liu-hz** [comment]
> adding a new profile

Thank you very much for dobefore's patient help. When I set up a new account, I can synchronize audio and pictures normally. You tell me adding a new profile, can I ask which profile is it?


There is another problem, many times the update requires the database to be checked. If it occurs again, it needs to be forced to synchronize. When forcing synchronization, if you choose to upload data locally, there will be show a user or password error, and then you need to log in again.


Is there any way to deal with this problem?
