### ISSUE TITLE
upload to ankiweb,   Or modify the card attributes,Error when uploading data

### ISSUE THREAD

**Issue by liu-hz** [ankicommunity/anki-sync-server#54]
In the anki desktop version, select in preferences to force one-way changes at the next synchronization. Then close anki, which prompts whether to upload or download. If you choose to upload, an error will be reported. You need to enter a user name and password, 

error code :"POST /sync/upload HTTP/1.1 " 403 157
ankisyncd.ThreadingColletionMnagaer:Monoitor is closing collection on inctive CollectionThread

anki desktop 2.1.35

which will appear repeatedly. Please help me , how can i fix this problem?Thank you very much!

**Comment by cecini** [comment]
https://stackoverflow.com/questions/51562067/connectionabortederror-winerror-10053-an-established-connection-was-aborted-b

**Comment by liu-hz** [comment]
> https://stackoverflow.com/questions/51562067/connectionabortederror-winerror-10053-an-established-connection-was-aborted-b

thank you cecini it nerver show the cord (os error 10053),but the user name or password error is still displayed.When I press the upload to ankiweb button on the anki desktop, show me the error ankiweb ID or password was incorrect, please try again.

This error still exists. It can be uploaded in anki Android, but it is reported in anki desktop 2.1.35

I would like to ask, how should this be handled, and then thank you for your efforts. Thank you very much.

![QQ截图20201110085318](https://user-images.githubusercontent.com/71445465/98614406-561d5800-2333-11eb-9f01-928d05e101c6.png)
![QQ截图20201110085332](https://user-images.githubusercontent.com/71445465/98614409-59184880-2333-11eb-9552-6f7ea1328837.png)

**Comment by AntonOfTheWoods** [comment]
Is this not when the URL hasn't been configured properly?

**Comment by liu-hz** [comment]
> Is this not when the URL hasn't been configured properly?
url is right just has a error,i can't fix.do you have this situation?I'm the only one to come across this problem?

**Comment by liu-hz** [comment]
error code :"POST /sync/upload HTTP/1.1 " 403 157
