### ISSUE TITLE
adding subdeck leads to sanity check failed on 2.1.36

### ISSUE THREAD

**Issue by dobefore** [ankicommunity/anki-sync-server#55]
I would like someone help me test whether my modified server code is right by taking the following actions:
@cecini sorry to bother you ,but need your help
- `create deck` -> `test::tt` On desktop Anki 2.1.36

-  Then hit sync On Desktop
- check if the `check database function` window will pop

It synced normally even though there was a subdeck before.However,today,I create a subdeck On desktop,Then sanity check failed on server output.
```
[2020-11-18 11:52:35,602]:INFO:ankisyncd.CollectionThread[puyuan]:Running sanityCheck2(*[], **{'client': [[0, 0, 0], 55558, 38730, 1035, 21, 17, 28, 2], 'full': True})
invalid current deck
[2020-11-18 11:52:35,715]:INFO:ankisyncd:sanity check failed with server: [[0, 0, 0], 55558, 38730, 1035, 21, 17, 27, 2] client: [[0, 0, 0], 55558, 38730, 1035, 21, 17, 28, 2] 

```
---
But after a while ,It back to normal(I guess the function automatically sync periodically works)
And after deleting the created subdeck,It returns back to normal too
Anki 2.1.36
anki mod 2.1.36

**Comment by cecini** [comment]
Please see  https://github.com/ankitects/anki/commit/7c57e5044bb83e5949ebb87346482124895409e0
Which fix the issue.

**Comment by dobefore** [comment]
Oh ,Thank you very much! It works perfectly.
