### ISSUE TITLE
Weird change in UI of AnkiDesktop after settiing up sync

### ISSUE THREAD

**Issue by samyak-jain** [ankicommunity/anki-sync-server#70]
Not sure why this is happening but I get a very weird change in the UI of the desktop app of Anki when I add the addon with the ```__init__.py``` as recommended in the documentation. The syncing works fine. 

As soon as I add the addon, this is how the UI starts looking like: 
![image](https://user-images.githubusercontent.com/10133258/104855743-820d1900-5934-11eb-847d-ff5282ae2c61.png)

Could this be a bug in Anki itself? Would love to know if anyone else is also facing this issue. 

```
Anki Version: anki 2.1.35-3
Platform: Linux (5.10.7-arch1-1)
```

**Comment by VikashKothary** [comment]
The README only contains the basic addon. Have a look here to see if it helps: https://github.com/ankicommunity/anki-desktop-addons. The "legacy" one is to be used for the anki-sync-server.

**Comment by samyak-jain** [comment]
I checked today and the issue seems to no longer exist. Must be a bug in anki that got fixed.
