### ISSUE TITLE
Can I sync data except the scheduling information.

### ISSUE THREAD

**Issue by karan-ta** [ankicommunity/anki-sync-server#81]
Hi,

I want to share the deck with few students daily.
So can I sync my deck to a server without the scheduling information ?

**Comment by VikashKothary** [comment]
Currently, you can not control which information is returned by the server. It's designed solely to sync data between the different devices.

It sounds like you're more interested in an API. I would suggest looking at https://github.com/ankicommunity/djankiserv to see if it fits your needs better.
