### ISSUE TITLE
Size limitation and conflict issue

### ISSUE THREAD

**Issue by vclst** [ankicommunity/anki-sync-server#86]
Hi, 

First of all thank you for your work. I have an anoying issue and I don't know if it is related to anki-sync-server, to a bad configuration or to anki internal limitations.

Indeed, I have a deck that is too big (more than the anki web limit) and therefore I am not able to sync my collection from Android application to my server: each time I have the message "Your collection or a media file is too large to sync".

I could live with it for a while, but recently I had a synchronization issue, and I have to force push my Android decks to my server - but I cannot do it due to the previous error. So, I'm not able anymore to add a card from my computer and synchronize it from my Android device.

So, my questions are:
- Is it possible to increase the size limitation on anki-sync-server? (I didn't find any documentation about that).
- Do the implementation of this feature is possible/planned?
- If not, any advice about what can I do?

Thank you in advance, and thank you again for maintening this application.

**Comment by Cfouria** [comment]
in nginx.conf i placed
client_max_body_size 222M;

**Comment by vclst** [comment]
Hello,

Indeed it works, thank you very munch! I had tried to increase the timeouts on nginx, but I did not known there was also a variable for the request size.

So it is definitely not related with anki-sync-server, nor anki. Thank you again and sorry for this useless issue.
